import type { Metadata } from "next";
import { Poppins } from 'next/font/google'
import "./globals.css";
import ConditionalLayout from "@/components/ConditionalLayout";
import Providers from "../../providers";
import { getSettings } from "@/lib/getSettings";
import { checkSetupStatus } from "@/lib/checkSetupStatus";
import SetupRedirect from "@/components/SetupRedirect";

const poppins = Poppins({ 
  subsets: ['latin'], 
  variable: '--font-poppins',
  weight: ['300', '400', '500', '600', '700']
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const settings = await getSettings();
  const setupStatus = await checkSetupStatus();

  return (
    <html lang="en">
      <body className={`${poppins.variable} antialiased bg-main`} >
        <Providers initialSettings={settings}>
          <SetupRedirect needsSetup={setupStatus.needsSetup} />
          <ConditionalLayout>
            {children}
          </ConditionalLayout>
        </Providers>
      </body>
    </html>
  );
}
