import type { Metadata } from "next";
import { Poppins } from 'next/font/google'
import "./globals.css";
import Layout from "@/components/layout/Layout";
import Providers from "../../providers";
import { getSettings } from "@/lib/getSettings";

const poppins = Poppins({ 
  subsets: ['latin'], 
  variable: '--font-poppins',
  weight: ['300', '400', '500', '600', '700']
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const settings = await getSettings();

  return (
    <html lang="en">
      <body className={`${poppins.variable} antialiased bg-main`} >
        <Providers initialSettings={settings}>
          <Layout>
            {children}
          </Layout>
        </Providers>
      </body>
    </html>
  );
}
